name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.23, 1.24]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: check go version
        run: go version
      - name: install dependencies
        run: go mod download
      - name: build application
        run: go build -v ./...
      - name: run tests
        run: go test -v ./... -coverprofile=coverage.out
      - name: upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.go-version }}
          path: coverage.out
          retention-days: 5

  display_result:
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report-${{ matrix.go-version }}
      - name: Display coverage report
        run: |
          value=$(cat coverage.out)
          echo "$value"
